#!/bin/bash
echo -e "\n"
echo -e "\n"
echo -e "\e[1m\e[92m     Python2 required for this to run."
echo -e "\n"
echo -e "\n"
echo -e "\e[91m\e[5m installing colorama"
pip2 install colorama
echo -e "\n"
echo -e "\e[91m\e[5m installing termcolor"
pip2 install termcolor
echo -e "\n"
echo -e "\e[91m\e[5m installing mechanize"
pip2 install mechanize
echo -e "\n"
echo -e "\e[91m\e[5m installing cookielib"
pip2 install cookielib
echo -e "\n"

echo -e "\n"
echo -e "\n"

echo -e "\e[91m Removing SETUP file"
rm setup
echo -e "\n"
echo -e "\e[92m\e[101m SETUP removed"
echo -e "\n"
echo -e "\e[91m Starting BruteFORCER..."
bash run
